module.exports = function() {
    return [
        { name: 'Game Of Thrones', showid:'Game-Of-Thrones', synopsis: 'George R.R. Martin\'s best-selling book series \'A Song of Ice and Fire\' is brought to the screen as HBO sinks its considerable storytelling teeth into the medieval fantasy epic. It\'s the depiction of two powerful families -- kings and queens, knights and renegades, liars and honest men -- playing a deadly game for control of the Seven Kingdoms of Westeros, and to sit atop the Iron Throne. Martin is credited as a co-executive producer and one of the writers for the series, whose shooting locations include Northern Ireland, Malta, Croatia and Spain.' },
        { name: 'The Haunting of Hill House', showid:'Haunting-Hill-House', synopsis: 'This modern reimagining of the Shirley Jackson novel follows siblings who, as children, grew up in what would go on to become the most famous haunted house in the country.. Now adults, they are forced back together in the face of tragedy and must finally confront the ghosts of their past. Some of those ghosts still lurk in their minds, while others may actually be stalking the shadows of Hill House. The ensemble cast includes Oscar winner Timothy Hutton, Carla Gugino and Henry Thomas. Mike Flanagan, a veteran of the horror genre, created the series.' },
        { name: 'Death Note', showid:'Death-Note', synopsis: 'Light Yagami (Tatsuya Fujiwara) is a normal, undistinguished college student -- that is, until he discovers an odd notebook lying on the ground. He soon discovers that the notebook has magic powers: If someone\'s name is written on it while the writer imagines that person\'s face, he or she will die. Intoxicated with his new godlike power, Light kills those he deems unworthy of life. But a mysterious detective known only as L (Ken\'ichi Matsuyama) becomes determined to put a stop to his reign.' },
        { name: 'Black Mirror', showid:'Black-Mirror', synopsis: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.' },
        { name: 'The Wire', showid:'The-Wire', synopsis: 'This series looks at the narcotics scene in Baltimore through the eyes of law enforcers as well as the drug dealers and users. Other facets of the city that are explored in the series are the government and bureaucracy, schools and the news media. The show was created by former police reporter David Simon, who also wrote many of the episodes.' },
        { name: 'The Walking Dead', showid:'The-Walking-Dead', synopsis: 'Based on the comic book series written by Robert Kirkman, this gritty drama portrays life in the months and years that follow a zombie apocalypse. Led by former police officer Rick Grimes, his family and a group of other survivors find themselves constantly on the move in search of a safe and secure home. But the pressure each day to stay alive sends many in the group to the deepest depths of human cruelty, and Rick discovers that the overwhelming fear of the survivors can be more deadly than the zombies walking among them.' },
    ];
};